export interface ReqencConfig {
  /**
   * Project API key generated by REQENC (e.g. "rqe_live_...").
   * Passed in `x-reqenc-key` header to authenticate against the edge proxy.
   */
  apiKey: string;

  /**
   * 2048-bit RSA-OAEP public key in PEM format.
   * Used to wrap ephemeral AES-256 session keys.
   */
  publicKey: string;

  /**
   * URL of your Cloudflare Anycast edge proxy (e.g. "https://proxy.reqenc.cwit.site").
   * Defaults to "https://proxy.reqenc.cwit.site".
   */
  proxyUrl?: string;

  /**
   * Protocol specification version. Defaults to "3".
   */
  version?: string;
}

export type ReqencInitOptions = Partial<ReqencConfig>;

export interface ReqencRequestOptions {
  /** HTTP method: GET, POST, PUT, DELETE, PATCH (defaults to POST) */
  method?: string;

  /** Custom request headers (sealed inside the 15-layer encrypted envelope) */
  headers?: Record<string, string>;

  /** Request body: JS object, string, or null */
  body?: any;

  /** Per-request API key override */
  apiKey?: string;

  /** Per-request Public Key override */
  publicKey?: string;

  /** Per-request Proxy URL override */
  proxyUrl?: string;

  /** Request timeout in milliseconds (default: 30000ms) */
  timeout?: number;
}

export interface EncryptedPacket {
  /** Protocol version ("3") */
  v: string;
  /** Ciphertext base64 (AES-256-GCM) */
  e: string;
  /** RSA-OAEP wrapped session key base64 */
  k: string;
  /** Initialization vector base64 */
  iv: string;
  /** 128-bit cryptographic nonce */
  n: string;
  /** Microsecond timestamp */
  t: number;
  /** Request trace UUID */
  rid: string;
  /** Public key fingerprint */
  kfp: string;
  /** Recursive double hash */
  dh: string;
  /** Size-bucket entropy padding */
  pad: string;
  /** HKDF derivation salt base64 */
  salt: string;
  /** Deflate compression flag */
  z: boolean;
  /** HMAC-SHA256 signature */
  s: string;
}

export interface ReqencResponse<T = any> {
  ok: boolean;
  status: number;
  statusText: string;
  headers: Headers;
  encryptedPacket: EncryptedPacket;
  json(): Promise<T>;
  text(): Promise<string>;
}
